import pathlib

import tkinter as tk
import tkinter.ttk as ttk
from tkinter.scrolledtext import ScrolledText



class GraficaApp:
    def __init__(self, master=None):
        # build ui
        self.toplevel2 = tk.Tk() if master is None else tk.Toplevel(master)
        self.frame6 = tk.Frame(self.toplevel2)
        self.menubutton11 = tk.Menubutton(self.frame6)
        self.menu2 = tk.Menu(self.menubutton11)
        self.mi_command2 = 1
        self.menu2.add('command', hidemargin='false', label='save')
        self.mi_command3 = 2
        self.menu2.add('command', label='exit')
        self.menubutton11.configure(direction='left', justify='left', state='normal', text='File')
        self.menubutton11.pack(side='left')
        self.menubutton16 = tk.Menubutton(self.frame6)
        self.menu7 = tk.Menu(self.menubutton16)
        self.mi_command10 = 1
        self.menu7.add('command', label='About')
        self.menubutton16.configure(text='Help')
        self.menubutton16.pack(side='left')
        self.frame6.configure(height='200', width='200')
        self.frame6.grid(column='0', row='0', sticky='w')
        self.frame7 = tk.Frame(self.toplevel2, container='false')
        self.label31 = tk.Label(self.frame7)
        self.label31.configure(compound='top', font='{Arial} 10 {bold}', justify='left', text='Data Entry')
        self.label31.place(anchor='nw', relwidth='0.12', relx='0.13', rely='0.06', x='0', y='0')
        self.label32 = tk.Label(self.frame7)
        self.label32.configure(relief='flat', text='Number of Acido Base Equilibria')
        self.label32.place(height='20', relheight='0.0', relwidth='0.0', relx='0.0', rely='0.0', width='200', y='60')
        self.menubutton10 = tk.Menubutton(self.frame7)
        self.menubutton10.configure(text='pH values')
        self.menubutton10.place(anchor='nw', x='60', y='310')
        self.__tkvar = tk.StringVar(value='')
        __values = ['One pH value', 'pH Range']
        self.optionmenu4 = tk.OptionMenu(self.frame7, self.__tkvar, 'One pH value', *__values, command=None)
        self.optionmenu4.place(anchor='nw', bordermode='inside', x='130', y='305')
        self.label40 = tk.Label(self.frame7)
        self.label40.configure(compound='top', justify='left', text='Single pH Value')
        self.label40.place(anchor='nw', x='50', y='350')
        self.entry38 = tk.Entry(self.frame7)
        self.entry38.place(anchor='nw', width='60', x='180', y='350')
        self.frame8 = tk.Frame(self.frame7)
        self.label33 = tk.Label(self.frame8)
        self.label33.configure(compound='top', justify='left', text='Enter the pKa values here')
        self.label33.place(anchor='nw', x='0', y='0')
        self.entry32 = tk.Entry(self.frame8)
        self.entry32.place(anchor='nw', width='60', x='50', y='30')
        self.label34 = tk.Label(self.frame8)
        self.label34.configure(compound='right', takefocus=False, text='pKa1=')
        self.label34.place(anchor='nw', x='0', y='28')
        self.entry33 = tk.Entry(self.frame8)
        self.entry33.place(anchor='nw', width='60', x='50', y='70')
        self.label35 = tk.Label(self.frame8)
        self.label35.configure(takefocus=False, text='pKa2=')
        self.label35.place(anchor='nw', x='0', y='68')
        self.label36 = tk.Label(self.frame8)
        self.label36.configure(takefocus=False, text='pKa3=')
        self.label36.place(anchor='nw', x='0', y='108')
        self.entry34 = tk.Entry(self.frame8)
        self.entry34.place(anchor='nw', width='60', x='50', y='110')
        self.entry35 = tk.Entry(self.frame8)
        self.entry35.place(anchor='nw', width='60', x='180', y='30')
        self.label37 = tk.Label(self.frame8)
        self.label37.configure(takefocus=False, text='pKa4=')
        self.label37.place(anchor='nw', x='130', y='28')
        self.entry36 = tk.Entry(self.frame8)
        self.entry36.place(anchor='nw', width='60', x='180', y='70')
        self.label38 = tk.Label(self.frame8)
        self.label38.configure(takefocus=False, text='pKa5=')
        self.label38.place(anchor='nw', x='130', y='68')
        self.label39 = tk.Label(self.frame8)
        self.label39.configure(takefocus=False, text='pKa6=')
        self.label39.place(anchor='nw', x='130', y='108')
        self.entry37 = tk.Entry(self.frame8)
        self.entry37.place(anchor='nw', width='60', x='180', y='110')
        self.button11 = tk.Button(self.frame8)
        self.button11.configure(text='ok')
        self.button11.place(anchor='nw', width='80', x='90', y='150')
        self.frame8.configure(borderwidth='1', height='200', highlightbackground='#000000', highlightcolor='#000000')
        self.frame8.configure(relief='groove', width='250')
        self.frame8.place(anchor='nw', bordermode='outside', x='35', y='100')
        self.frame9 = tk.Frame(self.frame7)
        self.label41 = tk.Label(self.frame9)
        self.label41.configure(compound='top', justify='left', text='Enter the pKa values here')
        self.label41.place(anchor='nw', x='0', y='0')
        self.entry39 = tk.Entry(self.frame9)
        self.entry39.place(anchor='nw', width='60', x='175', y='50')
        self.label42 = tk.Label(self.frame9)
        self.label42.configure(takefocus=False, text='Min')
        self.label42.place(anchor='nw', x='30', y='28')
        self.button12 = tk.Button(self.frame9)
        self.button12.configure(text='ok')
        self.button12.place(anchor='nw', bordermode='inside', width='40', x='240', y='35')
        self.entry40 = tk.Entry(self.frame9)
        self.entry40.place(anchor='nw', width='60', x='15', y='50')
        self.label43 = tk.Label(self.frame9)
        self.label43.configure(takefocus=False, text='Max')
        self.label43.place(anchor='nw', x='110', y='28')
        self.entry41 = tk.Entry(self.frame9)
        self.entry41.place(anchor='nw', width='60', x='95', y='50')
        self.label44 = tk.Label(self.frame9)
        self.label44.configure(takefocus=False, text='Step')
        self.label44.place(anchor='nw', x='190', y='28')
        self.frame9.configure(borderwidth='1', height='80', highlightbackground='#000000', highlightcolor='#000000')
        self.frame9.configure(relief='groove', width='300')
        self.frame9.place(anchor='nw', bordermode='outside', x='15', y='385')
        self.frame10 = tk.Frame(self.frame7)
        self.tkinterscrolledtext3 = ScrolledText(self.frame10)
        self.tkinterscrolledtext3.configure(width='480')
        self.tkinterscrolledtext3.place(anchor='nw', height='480', x='0', y='0')
        self.frame10.configure(borderwidth='1', height='480', relief='ridge', width='345')
        self.frame10.place(anchor='nw', x='350', y='0')
        __valuesa = ['1 pKa', '2 pKa']
        self.__tkvar2 = tk.StringVar()
        self.optionmenu1 = tk.OptionMenu(self.frame7, self.__tkvar2, None, *__valuesa, command=None)
        self.optionmenu1.place(anchor='nw', bordermode='inside', x='200', y='58')
        self.frame7.configure(height='485', takefocus=True, width='700')
        self.frame7.grid()
        self.toplevel2.configure(height='200', width='200')

        # Main widget
        self.mainwindow = self.toplevel2
    
    def run(self):
        self.mainwindow.mainloop()


if __name__ == '__main__':
    app = GraficaApp()
    app.run()
